/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR         0x40021000UL
#define RCC_CFGR_REG_OFFSET   0x04UL
#define RCC_CFGR_REG_ADDR     ( RCC_BASE_ADDR + CFGR_ENR_OFFSET )
#define GPIOA_BASE_ADDR       0x40010800UL

int main(void)
{
	uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;

	*pRccCfgrReg &= ~();
	for(;;);
}
