/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

const char *pMessage = "Hi there, Good Morning !";

const int value = 200;

char myData[50];

int main(void){
	for(uint32_t i = 0; i< strlen(pMessage); i++){
		myData[i] = *(pMessage+i);
	}
	for(;;);
}
