TEMPLATEROOT = /home/joswan/Descobrindo_STM32/STM32-Template

CFLAGS  += -O0 -g
ASFLAGS += -g

OBJS =  $(STARTUP) main.o
OBJS += stm32f10x_gpio.o stm32f10x_rcc.o

include $(TEMPLATEROOT)/Makefile.common
