TEMPLATEROOT = /home/joswan/Descobrindo_STM32/STM32-Template

# additional compilation flags

CFLAGS  += -O0 -g
ASFLAGS += -g

# projects files

OBJS = $(STARTUP) main.o
OBJS += stm32f10x_gpio.o stm32f10x_rcc.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common
